-- delete from teacher_entity;
-- insert into teacher_entity(t_id, t_last_name, t_name)  VALUES (6,'dsadsa 2','dsadsa 2');
-- insert into teacher_entity(t_id, t_last_name, t_name)  VALUES (3,'dsadsa 2','dsadsa 2');
-- insert into teacher_entity(t_id, t_last_name, t_name)  VALUES (4,'dsadsa 2','dsadsa 2');
-- insert into teacher_entity(t_id, t_last_name, t_name)  VALUES (5,'dsadsa 2','dsadsa 2');